setwd("../Dropbox/Coursera/Exploratory data analysis/Programming assignment 1")
dat <- read.csv("household_power_consumption.txt", sep=";", na.strings = "?", header=T, colClasses = c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
red <- subset(dat, as.character(dat$Date) == "1/2/2007" | as.character(dat$Date) == "2/2/2007")
data <- as.POSIXct(paste(red$Date, red$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
plot(red[,7] ~ data, type="l", pch=".", xlab="", ylab="Energy Sub Metering")
lines(red[,8] ~ data, col="red")
lines(red[,9] ~ data, col="blue")
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "Plot3.png")
dev.off()